# Generated by Django 3.1.2 on 2022-10-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(default='you default value or example@email.com', max_length=40, unique=True),
        ),
    ]
