# Generated by Django 3.1.2 on 2022-11-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='doctor',
            field=models.TextField(default='Doctor', max_length=100),
        ),
    ]
