# Generated by Django 3.1.2 on 2022-10-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_paciente_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
