# Generated by Django 3.1.2 on 2022-10-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20221025_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(default='example@email.com', max_length=40, unique=True),
        ),
    ]
