# Generated by Django 3.1.2 on 2022-11-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20221107_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialistas',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
