# Generated by Django 3.1.2 on 2022-11-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_especialistas_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialistas',
            name='password',
        ),
    ]
