# Generated by Django 3.1.2 on 2022-11-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_especialistas_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialistas',
            name='password',
            field=models.CharField(default='Contraseña', max_length=20),
        ),
    ]
