# Generated by Django 3.1.2 on 2022-10-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20221025_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='last_name',
        ),
    ]
