# Generated by Django 3.1.2 on 2022-11-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_especialistas_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialistas',
            old_name='password',
            new_name='password1',
        ),
    ]
