# Generated by Django 3.1.2 on 2022-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20221012_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idPaciente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
