# Generated by Django 3.1.2 on 2022-10-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20221025_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='username',
            field=models.CharField(max_length=150, verbose_name='username'),
        ),
    ]
