# Generated by Django 3.1.2 on 2022-11-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20221107_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialistas',
            old_name='password1',
            new_name='password',
        ),
    ]
