# Generated by Django 3.1.2 on 2022-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20221012_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='FechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
