# Generated by Django 3.1.2 on 2022-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20221012_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
