# Generated by Django 3.1.2 on 2022-11-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20221107_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=63)),
                ('password', models.CharField(max_length=63)),
            ],
            options={
                'verbose_name_plural': 'Login',
            },
        ),
    ]
