# Generated by Django 3.1.2 on 2022-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20221025_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesUsuarios',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='especialistas',
            name='correo',
            field=models.EmailField(default='example@email.com', max_length=40, unique=True),
        ),
    ]
