# Generated by Django 3.1.2 on 2022-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20221103_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesusuarios',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
